export const RouteNames = {
  signIn: '/sign-in',
  signUp: '/sign-up',
  home: '/home',
  catalog: '/catalog',
  catalogDetail: (id: string) => `/catalog/${id}`,
  vehicle: '/vehicle',
  simulator: '/simulator',
  simulatorSchedule: '/simulator/schedule',
  simulatorHistory: '/simulator/history',
  analytics: '/analytics',
  analyticsOverview: '/analytics/overview',
  analyticsCredit: '/analytics/credit',
  analyticsHistory: '/analytics/history',
  profile: '/profile',
  profileAccount: '/profile/account',
  profileSecurity: '/profile/security',
  profileHelp: '/profile/help',
  settings: '/settings',
  settingsGeneral: '/settings/general',
  settingsNotifications: '/settings/notifications',
  settingsAppearance: '/settings/appearance',
  paymentPlan: '/simulator/schedule',
  notifications: '/notifications',
  placeholder: '/placeholder',
} as const;